// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package exercise2;

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exercise2_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_exercise2_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\texercise2\".\n\007Message\022\n\n" +
      "\002fr\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\022\n\n\002to\030\003 \001(\005B\r\n\tex" +
      "ercise2P\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_exercise2_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_exercise2_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_exercise2_Message_descriptor,
        new java.lang.String[] { "Fr", "Msg", "To", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
