// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageHandShake.proto

package exercise2;

public interface MessageHandShakeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exercise2.MessageHandShake)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>optional bool error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>optional bool error = 2;</code>
   * @return The error.
   */
  boolean getError();
}
