// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageHandShake.proto

package exercise2;

public final class MessageHandShakeOuterClass {
  private MessageHandShakeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exercise2_MessageHandShake_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_exercise2_MessageHandShake_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026MessageHandShake.proto\022\texercise2\"-\n\020M" +
      "essageHandShake\022\n\n\002id\030\001 \001(\005\022\r\n\005error\030\002 \001" +
      "(\010B\r\n\texercise2P\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_exercise2_MessageHandShake_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_exercise2_MessageHandShake_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_exercise2_MessageHandShake_descriptor,
        new java.lang.String[] { "Id", "Error", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
